os: linux
arch:
 - amd64
 - ppc64le
language: python
python:
    - 2.7
    - pypy
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8
jobs: 
  exclude:
    - arch: ppc64le
      python: pypy
install:
    - "pip install requests"
script: nosetests
